### ISSUE TITLE
Support Markdown

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/gistexec#2]
I'm imagining it would be supported in a similar fashion to ipymd.

/cc @rossant

**Comment by rossant** [comment]
this is all client-side, right? I guess option 1 is to write a small JS port of ipymd, option 2 is to provide a REST API built on top of ipymd that converts documents between different formats (including ipynb and md)

**Comment by rgbkrk** [comment]
Ask and ye shall receive: #3.

**Comment by rgbkrk** [comment]
Example: https://lambdaops.com/gistexec/?gistID=4f38aa0f3546d3c84b8c

**Comment by rgbkrk** [comment]
This is definitely all client side. I just used marked. There are a couple strangenesses of using it this way:
- The kernel provided is always the last language detected in a code block
- Languages will only work if a kernel for that language is named the same as the kernel itself (we need a mapping)
